uniVote/elections/urls.py
from django.conf.urls import patterns, url

import views
import models

urlpatterns = patterns(
    '',

    # EX: /elections/
    url(r'^$',
        views.IndexView.as_view(),
        name='index'),

    # EX: /elections/alertUsers/
    url(r'^alertUsers/$',
        views.AlertUsers.as_view(),
        name='alertUsers'),

    # EX: /elections/sendingAlerts
    url(r'^sendingAlerts/$',
        views.sendAlerts,
        name='sendAlerts'),

    # EX: /elections/alertsSent
    url(r'^alertsSent/$',
        views.AlertsSent.as_view(),
        name='alertsSent'),

    # EX: /elections/monitor/
    url(r'^monitor/$',
        views.MonitorView.as_view(),
        name='monitor'),

    # EX: /elections/4
    url(r'^(?P<pk>\d+)/$',
        views.DetailView.as_view(),
        name='detail'),

    # EX: /elections/4/results
    url(r'^(?P<pk>\d+)/results/$',
        views.ResultsView.as_view(),
        name='results'),

    # EX: /elections/4/vote
    url(r'^(?P<election_id>\d+)/vote/$',
        views.vote,
        name='vote'),

    url(r'^election_register/(?P<election_id>\d+)/$',
        views.election_register,
        name='election_register'),

    # ex: /elections/4/voteform
    url(r'^(?P<pk>\d+)/voteform/$',
        views.VoteFormView.as_view(),
        name='voteform'),

    url(r'^profile/(?P<pk>\d+)/$',
        views.profile,
        name='profile'),

    url(r'^candidate_register/(?P<race_id>\d+)/$',
        views.candidate_register,
        name='candidate_register'),

    url(r'^(?P<pk>\d+)$',
        views.HybridDetailView.as_view(model=models.Voter)),
    )

uniVote/uniVote/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

# When a user requests a page from us, These URL patterns are checked first:
urlpatterns = patterns(
    '',
    # Examples:
    # EX: /
    url(r'', include('accounts.urls')),
    # EX: /elections/
    url(r'^elections/', include('elections.urls', namespace='elections')),
    # EX: /admin/
    url(r'^admin/', include(admin.site.urls)),
    # EX: accounts/...
    url(r'^accounts/', include('accounts.urls')),
)

uniVote/elections/models.py
from django.db import models
from django import forms
from django.utils import timezone as tz
from django.contrib.auth.models import User
from django.core.mail import EmailMessage

## AFTER CHANGING MODELS, issue commands makemigrations, migrate to save in db.

STATUS_CHOICES = (
    ('a', 'Approved'),
    ('n', 'Not Approved')
)


## Election class is represented in the db, it is a container for races
class Election(models.Model):
    def __unicode__(self):
        return self.election_text

    def in_election_window(self):
        if tz.now() > self.start_date and tz.now() < self.end_date:
            return True
        else:
            return False

    def is_closed(self):
        if tz.now() > self.end_date:
            return True
        else:
            return False

    election_text = models.CharField(max_length=200)
    start_date = models.DateTimeField('date election starts')
    end_date = models.DateTimeField('date election ends')

    in_election_window.admin_order_field = 'start_date'
    in_election_window.boolean = True
    in_election_window.short_description = 'In election window?'


## Race class represented in the database, it is a container for Candidates
class Race(models.Model):
    def __unicode__(self):
        return self.race_name

    # each race is related to an election
    election = models.ForeignKey(Election)
    race_name = models.CharField(max_length=200, default='')
    race_description = models.CharField(max_length=200, default='')
    race_detail = models.CharField(max_length=1000, default='')


# Each candiate is represented in the db.
# They are specifically bound to a race.
class Candidate(models.Model):
    def __unicode__(self):
        return self.user.first_name + " " + self.user.last_name

    # each Candidate is related to an race in an election
    race = models.ForeignKey(Race)
    election = models.ForeignKey(Election)
    ## Using the line below forces the admin to place a candidate in a race before
    ## creating an election. It's a catch-22.
    #user = models.ForeignKey(User, default='') #checking if this is causing a bug
    user = models.ForeignKey(User)

    #hold the number of votes
    num_of_votes = models.IntegerField(default=0)

## Hold data used in a candidate profile page.
class Profile(models.Model):
    def __unicode__(self):
        return self.id

    # Information stored in profile page
    #race = models.ForeignKey(Race)
    #election = models.ForeignKey(Election)
    candidate = models.ForeignKey(Candidate, default='')
    major = models.CharField(max_length=100, default='')
    interests = models.CharField(max_length=200, default='')
    experience = models.CharField(max_length=200, default='')


## Form to handle profile data
class ProfileForm(forms.Form):
    class Meta:
        model = Profile
        fields = ['major', 'interests', 'experience']


# Extending the existing User model to allow user to vote once per election:
# https://docs.djangoproject.com
# /en/1.7/topics/auth/customizing/#extending-the-existing-user-model
class Voter(models.Model):

    user = models.ForeignKey(User)
    election = models.ForeignKey(Election)
    is_approved = models.CharField(max_length=1, choices=STATUS_CHOICES, default='n')
    approved = models.BooleanField(default=False, editable=False)

    # bool value to check if the approval status has already been set to approved
    already_sent = models.BooleanField(default=False, editable=False)

    #bool to show if they have voted or not
    has_voted = models.BooleanField(default=False, editable=False)

    #store the confirmation num
    confirmation = models.CharField(max_length=40, default="")

    # send email when voters have been approved
    def send_approval_email(self):
        if self.already_sent:
            return
        else:
            user = str(self.user.username)
            election_name = str(self.election.election_text)
            email = EmailMessage("Voter Registration", "You have been approved to vote in the following election.\n\n"
                                                       "Username: " + user + "\n"
                                                       "Election: " + election_name + "\n\n"
                                                       "Thank you for using our system!"
                                                       "\nuniVote team", to=[self.user.email])
            email.send()
            return

    #check if they are approved
    def check_approval(self):
        if self.is_approved is "Approved":
            self.approved = True
            return True
        else:
            self.approved = False
            return False

    # Hold election information for each user
    # This is a dict that holds each election that the voter is approved for.
    # After voting, set that election to false, so they can no longer vote.
    #elections = {models.ForeignKey(Election): True}
    #approved = models.BooleanField(default=False)

    def add_election(self, election_object):
        self.elections.update({election_object: True})

    def delete_election(self, election_object):
        for i, test in self.elections:
            if i == election_object:
                del self.elections[i]
                break

    def update_vote_status(self, election_object):
        for i, test in self.elections:
            if i == election_object:
                # change from true to false
                if test:
                    self.elections[i] = False
                # change from false to true
                else:
                    self.elections[i] = True

    def as_dict(self):
        return {
            #'all_votes': self.all_votes,
            'id': self.id,
            'user': self.user,
            'election_id': self.election,
        }

    def __unicode__(self):
        return self.user.first_name + " " + self.user.last_name


## Stores votes in a table with foreign keys to respective attributes
class Votes(models.Model):

    # Votes are stored by votes cast for cand by voter in race
    race_voted_in = models.ForeignKey(Race)
    voter_who_voted = models.ForeignKey(Voter)
    candidate_voted_for = models.ForeignKey(Candidate)

uniVote/elections/templates/elections/alertUsers.html
{% extends "elections/base.html" %}
{% block content %}

<h1 style="display:inline-block;">Voter Alerts</h1>

<form style="display:inline-block;" action="/elections/sendingAlerts">
{% csrf_token %}
    <input id="sendAlertsButton" type="submit" value="Send Voter Alerts">
</form>

<p style="margin-left:4em;">Send voting alerts to users for the following active election(s):</p>
{% for election in active_elections %}
<h3><ul style="margin-left:4em;">{{ election }}</ul></h3>
{% endfor %}

{% endblock %}

{% block bottom %}
<br><hr>
<table>
    <tr>
        <td>
<a style="color:white; text-decoration:none; margin-left:2em; border: 1px solid white; border-radius:8px;
                    padding: 5px; background-color:#2064db; font-weight: bold;" href="/elections/">Return to Elections</a>
</td>
    </tr>

</table>
{% endblock %}

uniVote/elections/templates/elections/alertsSent.html
{% extends "elections/base.html" %}

{% block content %}

<h1>Alerts Sent!</h1>

{% endblock %}

{% block bottom %}
<br><hr>
<table>
    <tr>
        <td>
<a style="color:white; text-decoration:none; margin-left:2em; border: 1px solid white; border-radius:8px;
                    padding: 5px; background-color:#2064db; font-weight: bold;" href="/elections/">Return to Elections</a>
</td>
    </tr>
</table>
{% endblock %}

uniVote/elections/templates/elections/base.html
<link rel="shortcut icon" type="image/png" href="{{STATIC_URL}}images/favicon.png"/>
<link rel="stylesheet" href="{{ STATIC_URL }}homepage.css" />
<link rel="stylesheet" type="text/css" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css" />
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}lib/sweet-alert.css">
<script type="text/javascript" src="{{ STATIC_URL }}lib/sweet-alert.min.js"></script>
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL}}homescript.js"></script>


<script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '313812018825313',
        xfbml      : true,
        version    : 'v2.2'
      });
    };

    (function(d, s, id){
       var js, fjs = d.getElementsByTagName(s)[0];
       if (d.getElementById(id)) {return;}
       js = d.createElement(s); js.id = id;
       js.src = "//connect.facebook.net/en_US/sdk.js";
       fjs.parentNode.insertBefore(js, fjs);
     }(document, 'script', 'facebook-jssdk'));

	window.twttr=(function(d,s,id){var t,js,fjs=d.getElementsByTagName(s)[0];
		if(d.getElementById(id))
			{return}
		js=d.createElement(s);
		js.id=id;
		js.src="https://platform.twitter.com/widgets.js";
		fjs.parentNode.insertBefore(js,fjs);
		return window.twttr||(t={_e:[],ready:function(f){t._e.push(f)}})
	}(document,"script","twitter-wjs"));
</script>


<a id="logoutButton" href="{% url 'accounts.views.user_logout' %}">Logout</a>

{% if request.user.is_staff %}
    <p style="color: white; float: right;margin-top: 2em; margin-right: 1em; cursor: default;">|</p>
    <a id="adminButton" href="/admin/">Administration Panel</a>
    <p style="color: white; float: right;margin-top: 2em; margin-right: 1em; cursor: default;">|</p>
    <a id="alertButton" href="/elections/alertUsers/">Alert Users</a>
{% endif %}
    <a style="text-decoration: none;" href="/elections/">
	   <img id="uniLogo" src="/static/images/uniVote.png" />
    </a>
<br>
<div id="socialMedia">
	<div
	  class="fb-like"
	  data-share="true"
	  data-width="450"
	  data-show-faces="true">
	</div>
	<a class="twitter-share-button"
	  href="https://twitter.com/share">
	Tweet
	</a>
</div>

{% block content %}
<!-- Page content goes here. -->
{% endblock %}
{% block bottom %}
{% endblock %}

uniVote/elections/templates/elections/detail.html
{% extends "elections/base.html" %}
{% block content %}
<h1>{{ election.election_text }}</h1>


<!-- Cycle through all races assigned to an election -->
<!-- Start loop through races in this election and list race details -->
{% for race in election.race_set.all %}
<hr>
	<h3 style="padding-left:3em;"><strong>{{ race.race_name }}</strong></h3><h5 style="padding-left: 4.4em;">{{ race.race_description }}</h5>
	<p style="padding-left: 3.6em;">{{ race.race_detail }}</p>

	<table style="margin-left:10em;border:2px solid #2c3e50;border-radius:10px;background-color:#ecf0f1;"><th>List of Candidates</th>
 		<!-- Cycle through the candidates entered in this race, and post their details -->
 		{% for candidate in race.candidate_set.all %}
		<tr><td>{{ candidate.user.first_name }} {{ candidate.user.last_name }}<td>
			<td>
                <form style="margin:0;" method="POST" action="/elections/profile/{{ candidate.user_id }}/">
                    {% csrf_token %}
                    <input title="View this candidate's profile" type="image" style="height:30px;width:30px;margin-left:10px;" src="{{ STATIC_URL }}images/ProfilePicture.png"/></input>
                </form>
            </td>
		</tr>
 		{% endfor %} <!-- End candidate cycle -->

	</table>
<!-- Check to see if user is entered as a candidate in this race, if not then give add button -->
		{% for r, candidates in races.items %}

			<!-- if the race in the cycle equals the race in the dict, then do -->
			{% ifequal r race %}

				<!-- if the user is a candidate entered in this race, then message -->
				{% if user.id in candidates %}
				<p style="padding-left:3.6em;color:#c0392b;font-weight:bold;">You are a candidate in this race.</p>

				{% else %} <!-- Give button to enter as a candidate. -->
				<form action="/elections/candidate_register/{{ race.id }}/"method="post">
				{% csrf_token %}
					<input id="becomeCandidateButton" type="submit" value="Become a Candidate" />
				</form>
				{% endif %}

			{% endifequal %}

		{% endfor %}

 {% endfor %} <!-- End race cycle -->
 {% endblock %}

{% block bottom %}
<!-- Lower links of the voting form -->
<br><hr>
<table>
	<tr>
		<td><a style="color:white; text-decoration:none; margin-left:2em; border: 1px solid white; border-radius:8px;
                    padding: 5px; background-color:#2064db; font-weight: bold;" href="/elections/">Return to Elections</a></td>
	</tr>
</table>
{% endblock %}

uniVote/elections/templates/elections/index.html
{% extends "elections/base.html" %}

{% block content %}
<!-- If elections are created -->
{% if latest_election_list %}

    <br><br>
    <table id="t01">
        <tr>
            <col style="width:45px;">
            <col>
            <col>
            <col>
            <col>
            <th></th>
            <th style="text-align:left">Election Name</th>
            <th></th>
            <th>Start Time</th>
            <th>End Time</th>
        </tr>

    <!-- Cycles through all the elections created -->
    {% for election in latest_election_list %}

        <!-- The table row view when the election is open goes to voting page -->
        {% if election.in_election_window %}
        <tr class="electionList" style="color:blue">
            <td style="text-align:center;">
                <form style="margin:0;" class="regToVoteForm" method="POST" action="/elections/election_register/{{ election.id }}/">
                    {% csrf_token %}
                    <input title="Register to vote in this election." type="image" style="height:30px;width:30px;margin-left:10px;" src="{{ STATIC_URL }}images/registericon.png"/></input>
                </form>
            </td>
            <td><a style="color:blue;" class="electionList" href="{% url 'elections:voteform' election.id %}">{{ election.election_text }}</a>
            <td><a style="color:blue;" href="{% url 'elections:results' election.id %}">Statistics</a></td>
            <td id="td02">Open</td>
            <td id="td03">{{ election.end_date }}</td>
        </tr>

        <!-- The table row view when the election is over. Goes to a results page -->
        {% elif election.is_closed %}
        <tr class="electionList" style="color:blue">
            <td></td>
            <td><a style="color:blue;" class="electionList" href="{% url 'elections:detail' election.id %}">{{ election.election_text }}</a>
            <td><a style="color:blue;" href="{% url 'elections:results' election.id %}">Statistics</a></td>
            <td id="td02">Closed</td>
            <td id="td03">Closed</td>
        </tr>

        <!-- The table row displayed before the election opens. Goes to the details page -->
        {% else %}
        <tr class="electionList" style="color:blue">
            <td style="text-align:center;">
                <form style="margin:0;" class="regToVoteForm" method="POST" action="/elections/election_register/{{ election.id }}/">
                    {% csrf_token %}
                    <input title="Register to vote in this election." type="image" style="height:30px;width:30px;margin-left:10px;" src="{{ STATIC_URL }}images/registericon.png"/></input>
                </form>
            </td>
            <td><a style="color:blue;" class="electionList" href="{% url 'elections:detail' election.id %}">{{ election.election_text }}</a>
            <td></td>
            <td id="td02">{{ election.start_date }}</td>
            <td id="td03">{{ election.end_date }}</td>
        {% endif %}
        </tr>
    {% endfor %}
<!-- Displays when no elections are available -->
{% else %}
    <p id="noElects">No polls are available.</p>
{% endif %}
	</table>
{% endblock %}
{% block bottom %}
{% endblock %}

uniVote/elections/templates/elections/monitor.html
{% extends "elections/base.html" %}
{% block content %}

<h1>Election Monitoring</h1>

<h2>{{ election.election_text }}</h2>

<!-- Show a list of results in a table for admins or monitors only FOR NOW -->
{% for race, candidates in races.items %}
    <h4>{{ race }}</h4>
    {% for candidate in candidates %}
        {% for cand, num_votes in votes.items %}
            <p style="margin-left: 2em;">{{ candidate }}
            {% ifequal cand.user.last_name candidate %}
             - {{ num_votes }}
            {% endifequal %}
            </p>
        {% endfor %}
    {% endfor %}
{% endfor %}

{% endblock %}

{% block bottom %}
<br><hr>
<table>
	<tr>
		<td>
<a style="color:white; text-decoration:none; margin-left:2em; border: 1px solid white; border-radius:8px;
                    padding: 5px; background-color:#2064db; font-weight: bold;" href="/elections/">Return to Elections</a>
</td>
	</tr>
</table>
{% endblock %}

uniVote/elections/templates/elections/profile.html
{% extends "elections/base.html" %}
{% block content %}
<br><br>
<!-- This section is for when there is no profile for the candidate -->
{% if error_message %}
	<h1>{{ candidate }}</h1>
	<p>{{ error_message }} </p>
	
	<!-- Check if the user IS the candidate in the profile, then display the form -->
	{% ifequal user.id candidate.user_id %}
	<form action="/elections/profile/{{ candidate.user_id }}/" method="POST">
	{% csrf_token %}
		<!-- Insert profile fields here -->
	<hr>
	<table><th>Create Profile</th>
		<tr>
			<td><label for="candidate.user_id">Major: </label></td>
			<td><input id="major" type="text" name="major" values="{{ major }}"></td>
		</tr>
		<tr>
			<td><label for="candidate.user_id">Interests: </label></td>
			<td><input id="interests" type="text" name="interests" value="{{ interests }}"></td>
		</tr>
		<tr>
			<td><label for="candidate.user_id">Experience:</label></td>
			<td><input id="experience" type="text" name="experience" value="{{ experience }}"></td>
		</tr>
	</table>
        <input id="saveProfileButton" type="submit" value="Save">
	</form>
	{% endifequal %}
	
	{% if request.user.is_staff %}
	<!-- If user is an admin, they can edit the field. -->
	<form action="/elections/profile/{{ candidate.user_id }}/" method="POST">
	{% csrf_token %}
		<!-- Insert profile fields here -->
	<hr>
	<table><th>Edit Profile</th>
		<tr>
			<td><label for="candidate.user_id">Major: </label></td>
			<td><input id="major" type="text" name="major" values="{{ major }}"></td>
		</tr>
		<tr>
			<td><label for="candidate.user_id">Interests: </label></td>
			<td><input id="interests" type="text" name="interests" value="{{ interests }}"></td>
		</tr>
		<tr>
			<td><label for="candidate.user_id">Experience:</label></td>
			<td><input id="experience" type="text" name="experience" value="{{ experience }}"></td>
		</tr>
	</table>
        <input id="saveProfileButton" type="submit" value="Save">
	</form>
	{% endif %}
	
{% else %} <!-- A profile already exists for the candidate -->
<h1>{{ candidate }}</h1>
<h3>Candidate Profile:</h3>
	<table>
		<tr>
			<td>Major:</td><td>{{ profile.major }}</td>
		</tr>
			<td>Experience:</td><td>{{ profile.interests }}</td>
		</tr>
		<tr>
			<td>Interests:</td><td>{{ profile.experience }}</td>
		</tr>
	</table>
	<!-- Display a form for editing if the user IS the candidate -->
	{% ifequal user.id candidate.user_id %}
	<form action="/elections/profile/{{ candidate.user_id }}/" method="POST">
	{% csrf_token %}
		<!-- Insert profile fields here -->
		<hr>
		<table><th>Edit Profile</th>
			<tr>
				<td><label for="candidate.user_id">Major: </label></td>
				<td><input id="major" type="text" name="major" values="{{ major }}"></td>
			</tr>
			<tr>
				<td><label for="candidate.user_id">Interests: </label></td>
				<td><input id="interests" type="text" name="interests" value="{{ interests }}"></td>
			</tr>
			<tr>
				<td><label for="candidate.user_id">Experience:</label></td>
				<td><input id="experience" type="text" name="experience" value="{{ experience }}"></td>
			</tr>
		</table>
        <input id="saveProfileButton" type="submit" value="Save">
	{% endifequal %}
	
	{% if request.user.is_staff %}
	<!-- If user is an admin, they can edit the field. -->
	<form action="/elections/profile/{{ candidate.user_id }}/" method="POST">
	{% csrf_token %}
		<!-- Insert profile fields here -->
	<hr>
	<table><th>Edit Profile</th>
		<tr>
			<td><label for="candidate.user_id">Major: </label></td>
			<td><input id="major" type="text" name="major" values="{{ major }}"></td>
		</tr>
		<tr>
			<td><label for="candidate.user_id">Interests: </label></td>
			<td><input id="interests" type="text" name="interests" value="{{ interests }}"></td>
		</tr>
		<tr>
			<td><label for="candidate.user_id">Experience:</label></td>
			<td><input id="experience" type="text" name="experience" value="{{ experience }}"></td>
		</tr>
	</table>
        <input id="saveProfileButton" type="submit" value="Save">
	</form>
	{% endif %}
{% endif %}
{% endblock %}
{% block bottom %}
<!-- Lower links of the voting form -->
<br><hr>
<table>
	<tr>
		<td>
<a style="color:white; text-decoration:none; margin-left:2em; border: 1px solid white; border-radius:8px;
                    padding: 5px; background-color:#2064db; font-weight: bold;" href="/elections/">Return to Elections</a>
</td>
	</tr>
</table>
{% endblock %}

uniVote/elections/templates/elections/results.html
{% extends "elections/base.html" %}


{% block content %}
<script type="text/javascript" src="{{ STATIC_URL }}statistics.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}lib/Chart.js"></script>

<h1>{{ election.election_text }}</h1>
    <hr>
			{% for race in election.race_set.all %}

				<h3 style="text-align:center;">{{ race.race_name }}</h3>
                <canvas class="myChart" width="800" height="400" style="margin-left:auto;margin-right:auto;margin-bottom:2em;display:block;">
				{% for candidate in race.candidate_set.all %}
                    <div class="graphData" style="display:none;">
						<p class="candidates" >{{ candidate.user.first_name }} {{ candidate.user.last_name }}</p>
                        <p class="votes" >{{ candidate.num_of_votes }}</p>
                        <p class="counter" >{{ forloop.parentloop.counter0 }}</p>
                    </div>
				{% endfor %}
                </canvas>

    <hr>
			{% endfor %}

</table>









{% endblock %}
{% block bottom %}
<br>
<table>
    <tr>
        <td>
<a style="color:white; text-decoration:none; margin-left:2em; border: 1px solid white; border-radius:8px;
                    padding: 5px; background-color:#2064db; font-weight: bold;" href="/elections/">Return to Elections</a>
</td>
    </tr>
</table>
{% endblock %}

uniVote/elections/templates/elections/voteform.html
{% extends "elections/base.html" %}


{% block content %}
<link rel="stylesheet" href="{{ STATIC_URL }}voteform.css" />
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}lib/sweet-alert.css">
<script type="text/javascript" src="{{ STATIC_URL }}lib/sweet-alert.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL}}votescript.js"></script>




<h1>{{ election.election_text }} Elections</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<!-- Start form - from and sent to corresponding /'election_id'/vote  page -->
<form id="voteForm" action="{% url 'elections:vote' election.id %}" method="post">
{% csrf_token %}

<!-- Cycle through all races assigned to an election -->
{% for race in election.race_set.all %}
	<fieldset class = "radiogroup">
	<input type="hidden" name="race_id[]" value="{{race.id}}">
	<legend style="font-weight:bold;"><label for="race{{ forloop.counter }}">
	   {{ race.race_name }}</label></legend>
	<p style="margin-left:1em;">{{ race.race_description }}</p>
	
	<table style="margin-left:4em;">
	<!-- Cycle through all the candidates in the given race -->	
	{% for candidate in race.candidate_set.all %} 

		<tr>
			<td><input type="radio" name="candidate_race_{{race.id}}"
				 value="{{ candidate.id }}" /><label for="race_{{race.id}}">
				 {{ candidate.user.first_name }} {{ candidate.user.last_name }}</label></td>
			<td>  <a href="/elections/profile/{{ candidate.user_id }}/" title="View this candidate's profile" style="height:30px;width:30px;margin-left:10px;"><img style="height:30px;width:30px;margin-left:10px;" src="{{ STATIC_URL }}images/ProfilePicture.png"/></a>
		</tr>
	{% endfor %} <!-- End candidate cycle -->
	</table>
	</fieldset>
	<br><br>
{% endfor %} <!-- End race cycle -->

<!-- Form submit -->
<input id="voteButton" type="submit" value="Vote!" />
</form>
{% endblock %}

{% block bottom %}
<!-- Lower links of the voting form -->
<br><hr>
<table>
	<tr>
		<td>
<a style="color:white; text-decoration:none; margin-left:2em; border: 1px solid white; border-radius:8px;
                    padding: 5px; background-color:#2064db; font-weight: bold;" href="/elections/">Return to Elections</a>
</td>
	</tr>

</table>
{% endblock %}